name = "cs-resume-critique-api"
main = "src/index.ts"
compatibility_date = "2026-07-15"

[ai]
binding = "AI"

routes = [
  { pattern = "critique.superjeffc.com/api/*", zone_name = "superjeffc.com" }
]
